steps:
    - name: maven:3-jdk-8
      entrypoint: mvn
      args:
        - 'clean'
        - 'package'
        - 'appengine:deploy'
        - '-Dapp.deploy.promote=False'
        - '-Dapp.deploy.version=$_PR_NUMBER'
        - '-Dapp.deploy.projectId=$PROJECT_ID'
