name: Lint Code Base

on:
    pull_request:
        branches: [ master ]

###############
# Set the Job #
###############
jobs:
    build:
        # Name the Job
        name: Lint Code Base
        # Set the agent to run on
        runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
        - name: Checkout Code
        uses: actions/checkout@v2

        - name: Run a one-line script
        run: echo Hello, world!

        - name: Lint Code Base
        uses: docker://github/super-linter:v2.2.0
        env:
            VALIDATE_ALL_CODEBASE: false
            VALIDATE_ANSIBLE: false
